In [303]:
#import the required libraries

import numpy as np
import pandas as pd

# Step 1 : Read the Data!

In [304]:
#give path of the source-file and store that path in a variable named census

census = pd.read_csv("C:\\Users\\Admin\\Downloads\\makeSenseOfCensus.csv")
census

age  education-num  race  sex  capital-gain  capital-loss  \
0     39             13     4    1          2174             0   
1     50             13     4    1             0             0   
2     38              9     4    1             0             0   
3     53              7     2    1             0             0   
4     28             13     2    0             0             0   
..   ...            ...   ...  ...           ...           ...   
995   56              9     4    1             0             0   
996   45             14     4    1             0             0   
997   48             13     4    1             0             0   
998   40             10     4    1          2580             0   
999   39             13     4    1         15024             0   

     hours-per-week  income  
0                40       0  
1                13       0  
2                40       0  
3                40       0  
4                40       0  
..              ...     ...  
995              55       1  
996              45       0  
997              58       1  
998              40       0  
999              50       1  

[1000 rows x 8 columns]

# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [305]:
import numpy as np

# # Specify the path to your file
census = "C:\\Users\\Admin\\Downloads\\makeSenseOfCensus.csv"

# Read the data into a NumPy array
census = np.genfromtxt(census, delimiter=',', skip_header=1)

# Print the output
print(census)


[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [306]:
#print the type of data
print(census.dtype)

float64


# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [307]:
new_record = [[50,9,4,1,0,0,40,0]]
data = census

con_data = np.concatenate([data, new_record])
con_data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [308]:
#display after appending the new record at the end of them
new_record

[[50, 9, 4, 1, 0, 0, 40, 0]]

# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [309]:
age_col = con_data[:,0]

age_col

array([39., 50., 38., ..., 40., 39., 50.])

In [310]:
# Calculate the median age
median_age = np.median(age_col)

# Define the threshold for classification
threshold = 30  # You can adjust this value as needed

# Classify as "young country" or "old country"
country_type = np.where(median_age < threshold, "young Country", "old Country")

# Print the results
print("Median Age:", median_age)
print("Country Type:", country_type)


Median Age: 36.0
Country Type: old Country


Find the max age and store it in a variable called 'max_age'.



In [311]:
#print the max_age

max_age = np.max(age_col)

print(f"The Maximum Age is :{max_age}")



The Maximum Age is :90.0


Find the min age and store it in a variable called 'min_age'.

In [312]:
#print the min_age
min_age = np.min(age_col)

print(f"The Manimum Age is :{min_age}")

The Manimum Age is :17.0


Find the mean of the age and store it in a variable called 'age_mean'.

In [322]:
#print the age_mean

mean_age = np.mean(age_col)

print(f"The Mean Age is :{mean_age}")


The Mean Age is :38.06293706293706


Find the standard deviation of the age and store it in a variable called 'age_std'

In [323]:
#print the age_std

std_age = np.std(age_col)

print(f"The std Age is :{mean_age}")

The std Age is :38.06293706293706


# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [315]:
#len_0

In [316]:
#len_1

In [317]:
#len_2

In [318]:
#len_3

In [319]:
#len_4

Find out which is the race with the minimum no. of citizens

Find out which is the race with the minimum no. of citizens

Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [320]:
#from age column, filter out age data > 60

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

e. Print 'avg_working_hours' and see if the govt. policy is followed.

# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.